const projects={
  hobby:{type:"Community platform · Product design",title:"Hobby Ghar",summary:"A connected community surface for discovering local interests, events, clubs and specialist shops.",problem:"Interest-led activity is often scattered across social feeds, messaging groups, event listings and separate stores.",focus:"Create one understandable path from discovering an interest to finding a community and taking part.",role:"Product and UI/UX design. Exact team ownership and delivery details will be confirmed before the full page is published.",status:"Live product work · detailed evidence inventory pending."},
  ctf:{type:"Cybersecurity · UX + frontend",title:"CTF Platform",summary:"A structured practice environment for learning security through progressive challenges.",problem:"Learners need enough guidance to begin without removing the discovery and problem-solving that make a challenge valuable.",focus:"Balance challenge clarity, progression, feedback and technical context across the learning journey.",role:"UX design and frontend contribution. Detailed collaboration boundaries will be added with the final artifacts.",status:"Project preview · implementation evidence pending."},
  job:{type:"Career technology · Product concept",title:"Job & Skill",summary:"A career product connecting opportunities with the skills needed to become ready for them.",problem:"Job listings show requirements but rarely turn the gap between a candidate and a role into an actionable path.",focus:"Connect role fit, missing skills and practical next steps without presenting uncertain matching as fact.",role:"Product concept and interface design.",status:"Concept · intended outcomes are not presented as achieved metrics."},
  molly:{type:"Digital product · UI/UX",title:"Molly.CO",summary:"A responsive digital experience developed through UI/UX and frontend collaboration.",problem:"The project needed a coherent experience across screen sizes while preserving a distinctive visual identity.",focus:"Responsive hierarchy, reusable interface patterns and a clear design-to-build relationship.",role:"UI/UX design with frontend collaboration. Exact scope will be confirmed before the detailed page.",status:"Project preview · final content and mockups pending."},
  med:{type:"Healthcare · Mobile UX",title:"MedTrack",summary:"A clearer daily system for medication and health routines.",problem:"Remembering what to take, when to take it and whether it was completed can become an avoidable cognitive burden.",focus:"Make the next required action visible while keeping history, reminders and status understandable.",role:"Mobile UX concept and interface design.",status:"Concept · no clinical or outcome claims are made."},
  solar:{type:"Sustainability · Web experience",title:"Solar",summary:"A web experience that makes residential solar information easier to understand and compare.",problem:"People evaluating solar can face unfamiliar terminology, uncertain savings and choices that are difficult to compare.",focus:"Translate technical inputs into a transparent decision path without overstating estimated outcomes.",role:"Web UX and interface concept.",status:"Concept · calculations shown in previews are illustrative only."}
};

const dialog=document.querySelector('#project-dialog');
const fields={type:document.querySelector('#dialog-type'),title:document.querySelector('#dialog-title'),summary:document.querySelector('#dialog-summary'),problem:document.querySelector('#dialog-problem'),focus:document.querySelector('#dialog-focus'),role:document.querySelector('#dialog-role'),status:document.querySelector('#dialog-status')};
let opener;
document.querySelectorAll('.project-open').forEach(button=>button.addEventListener('click',()=>{opener=button;const data=projects[button.closest('.project-row').dataset.project];Object.keys(fields).forEach(key=>fields[key].textContent=data[key]);dialog.showModal()}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
dialog.addEventListener('close',()=>opener?.focus());

const filters=[...document.querySelectorAll('.filter')];
const rows=[...document.querySelectorAll('.project-row')];
filters.forEach(filter=>filter.addEventListener('click',()=>{filters.forEach(item=>{const active=item===filter;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});const value=filter.dataset.filter;rows.forEach(row=>row.hidden=value!=='all'&&row.dataset.kind!==value);document.querySelector('.empty-state').hidden=rows.some(row=>!row.hidden)}));
